# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956b7fd26104fc93931c01c10ff9f98818e06da3821773e412cde3e63912359a28aaab424a74eabe73e4ee40692b70e9dd54988e33b0a64e9e458779908e09d3

test:
  secret_key_base: aaae98f6abb710dff2e2c4f7451c5383df1e20bac5a802857218f1d0f1102a612cfc7cd0df636dc50539fef723443dcedba4622186605a9704b2176837f94e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
